-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.user_profiles
    ADD COLUMN current_org_id bigint;

ALTER TABLE IF EXISTS public.user_profiles
    ADD COLUMN current_org_position text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.user_profiles
    ADD CONSTRAINT user_profiles_current_org_id_fkey FOREIGN KEY (current_org_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
