-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: deal_comment_type
CREATE TYPE public.deal_comment_type AS ENUM
    ('ANNOUNCEMENT', 'FAQ');

ALTER TYPE public.deal_comment_type
    OWNER TO supabase_admin;

ALTER TABLE IF EXISTS public.deal_comments
    ADD COLUMN deal_id bigint NOT NULL;

ALTER TABLE IF EXISTS public.deal_comments
    ADD COLUMN type deal_comment_type;

ALTER TABLE IF EXISTS public.deal_comments
    ADD CONSTRAINT deal_comments_deal_id_fkey FOREIGN KEY (deal_id)
    REFERENCES public.deals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
