-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER FUNCTION public.create_user_profile_on_user_creation()
    SET search_path=public;

CREATE OR REPLACE VIEW public.inbox_conversation_view
 AS
 SELECT conv.id AS conversation_id,
    conv.is_marked_done,
    conv.title,
    conv.updated_at,
    ( SELECT json_agg(chat_users.*) AS json_agg
           FROM ( SELECT other_user.user_id,
                    other_user.profile_pic_url,
                    other_user.handle,
                    other_user.subtitle,
                    other_user.first_name,
                    other_user.last_name
                   FROM conversation_to_user_associations ctua
                     JOIN user_profiles other_user ON ctua.user_id = other_user.user_id
                  WHERE ctua.conversation_id = conv.id) chat_users) AS users_in_conv,
    ( SELECT json_agg(all_messages.*) AS json_agg
           FROM ( SELECT message.id,
                    message.user_id,
                    sender_user.first_name AS sender_user_first_name,
                    sender_user.last_name AS sender_user_last_name,
                    sender_user.handle AS sender_user_handle,
                    sender_user.profile_pic_url AS sender_user_profile_pic_url,
                    message.content,
                    message.created_at,
                    message.nudged_time,
                    message.on_deal_id,
                    deal.title AS deal_title,
                    deal.handle AS deal_handle,
                    deal.about AS deal_about,
                    ( SELECT deal_image.image_url
                           FROM deal_images deal_image
                          WHERE deal_image.deal_id = message.on_deal_id
                          ORDER BY deal_image.order_index) AS deal_image,
                    ( SELECT json_agg(all_read_receipts.*) AS json_agg
                           FROM ( SELECT mrr.id,
                                    mrr.created_at,
                                    mrr.updated_at,
                                    mrr.user_id,
                                    mrr.message_id
                                   FROM message_read_receipts mrr
                                  WHERE mrr.message_id = message.id) all_read_receipts) AS json_agg
                   FROM messages message
                     JOIN user_profiles sender_user ON sender_user.user_id = message.user_id
                     LEFT JOIN deals deal ON deal.id = message.on_deal_id
                  WHERE message.conversation_id = conv.id) all_messages) AS json_agg
   FROM conversations conv
  ORDER BY conv.id;

ALTER TABLE public.inbox_conversation_view
    OWNER TO supabase_admin;

GRANT ALL ON TABLE public.inbox_conversation_view TO anon;
GRANT ALL ON TABLE public.inbox_conversation_view TO postgres;
GRANT ALL ON TABLE public.inbox_conversation_view TO supabase_admin;
GRANT ALL ON TABLE public.inbox_conversation_view TO authenticated;
GRANT ALL ON TABLE public.inbox_conversation_view TO service_role;
