CREATE TYPE public.notification_type AS ENUM
    ('LikedYourPost', 'PostedAComment', 'ExpressedInterestInYourDeal', 'HasAcceptedYourConnectionRequest', 'WroteYouAnEndorsement', 'AddedYouAsATeamMember', 'ReferredYouToANewDeal');

ALTER TYPE public.notification_type
    OWNER TO supabase_admin;

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    receiving_user_id uuid NOT NULL,
    from_user_id uuid NOT NULL,
    is_seen boolean NOT NULL DEFAULT false,
    debug_info text COLLATE pg_catalog."default",
    attached_deal_id bigint,
    attached_org_id bigint,
    notification_type notification_type NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_attached_deal_id_fkey FOREIGN KEY (attached_deal_id)
        REFERENCES public.deals (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT notifications_attached_org_id_fkey FOREIGN KEY (attached_org_id)
        REFERENCES public.organizations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT notifications_from_user_id_fkey FOREIGN KEY (from_user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT notifications_receiving_user_id_fkey FOREIGN KEY (receiving_user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT chk_at_most_one_is_not_null CHECK (num_nonnulls(attached_deal_id, attached_org_id) < 2)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.notifications
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.notifications
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.notifications TO authenticated;

GRANT ALL ON TABLE public.notifications TO anon;

GRANT ALL ON TABLE public.notifications TO postgres;

GRANT ALL ON TABLE public.notifications TO service_role;

GRANT ALL ON TABLE public.notifications TO supabase_admin;
