CREATE TABLE IF NOT EXISTS public.waitlist_emails
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    email text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT waitlist_emails_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.waitlist_emails
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.waitlist_emails TO anon;

GRANT ALL ON TABLE public.waitlist_emails TO authenticated;

GRANT ALL ON TABLE public.waitlist_emails TO postgres;

GRANT ALL ON TABLE public.waitlist_emails TO service_role;

GRANT ALL ON TABLE public.waitlist_emails TO supabase_admin;

CREATE TRIGGER waitlist_emails_set_updated_at
    BEFORE INSERT OR UPDATE 
    ON public.waitlist_emails
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS public.deal_attachment_stats
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    view_count bigint NOT NULL DEFAULT '0'::bigint,
    progress bigint NOT NULL DEFAULT '0'::bigint,
    deal_attachment_id bigint NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT deal_attachment_stats_pkey PRIMARY KEY (id),
    CONSTRAINT deal_attachment_stats_deal_attachment_id_fkey FOREIGN KEY (deal_attachment_id)
        REFERENCES public.deal_attachments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT deal_attachment_stats_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.user_profiles (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.deal_attachment_stats
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.deal_attachment_stats TO anon;

GRANT ALL ON TABLE public.deal_attachment_stats TO authenticated;

GRANT ALL ON TABLE public.deal_attachment_stats TO postgres;

GRANT ALL ON TABLE public.deal_attachment_stats TO service_role;

GRANT ALL ON TABLE public.deal_attachment_stats TO supabase_admin;

CREATE TRIGGER deal_attachment_stats_set_updated_at
    BEFORE INSERT OR UPDATE 
    ON public.deal_attachment_stats
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_set_updated_at();

ALTER TABLE IF EXISTS public.endorsements
    ALTER COLUMN relationship DROP NOT NULL;

ALTER TABLE IF EXISTS public.deal_attachments
    ADD COLUMN total_num_pages bigint;
